# Generated by Django 5.0.2 on 2024-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_email_id', models.EmailField(max_length=30)),
                ('emp_gender', models.CharField(max_length=20)),
                ('emp_phone', models.CharField(max_length=20)),
                ('emp_dept', models.CharField(max_length=20)),
            ],
        ),
    ]
