# Generated by Django 5.0.2 on 2024-02-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
